name: Automatic tests

on:
  pull_request:
    branches: [ master ]

jobs:
  test_codebase:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@2
      - name: Set up JDK 1.11
        uses: actions/setup_java@v1
        with:
          java-version: 1.11
      - name: Build with Maven
        run: mvn -B package --file pom.xml

